extends Node

#Entity
enum ET{PLAYER, SAP_SLIME, GOBBLER}

#Player Enums
enum PS{IDLE, RUN, FURY, HIT, DEAD, DODGE, ATTACK}
enum AT{PROJ, SWING}
enum AG{CATEGORY, SPRITE, NUM_WINDOWS, 
	WINDOW_LENGTH, WINDOW_GOTO, NUM_WINDOWS, WINDOW_TYPE, WINDOW_HAS_SFX, 
	WINDOW_SFX, WINDOW_SFX_FRAME, WINDOW_ANIM_FRAMES, WINDOW_ANIM_FRAME_START,
	WINDOW_SPEED, WINDOW_SPEED_TYPE, WINDOW_HAS_CUSTOM_FRICTION, WINDOW_CUSTOM_FRICTION}
enum HG{HITBOX_TYPE, WINDOW, WINDOW_CREATION_FRAME,
		LIFETIME, HITBOX_FORW, HITBOX_SIDE,
		WIDTH, HEIGHT, DAMAGE, KNOCKBACK, HITSTUN}

#Sap Slime enums
enum SS_PS{IDLE, WALK, HIT, ATTACK, DEAD}
enum SS_AT{LUNGE}
